In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# import sys

# !{sys.executable} -m pip install linearmodels

# сгенерируем синтетические данные

In [3]:
import pandas as pd
import numpy as np

In [4]:
from data_gen import DataGenerator

In [5]:
df_gen = DataGenerator(
    n_samples = 10_000,
    time_correlations={
        'X1': 0.3,
        'X2': 0.2,
        'y0': 0.8
    },
    distributions = {
        'X1': {'type': 'normal', 'mean': 1, 'std': 2},
        'X2': {'type': 'bernoulli', 'p': 0.4},
        'y0': {'type': 'normal', 'mean': 10, 'std': 4}
    },
    effect_size = 5.0,
    seed = 1114,
)

df = df_gen.generate()

In [6]:
df.describe()

,X1,X1_lag,X2,X2_lag,y0,y0_lag_1,y0_lag_2,z,U,D,d,y1,y
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1.014193,1.000744,0.406100,0.393700,9.930242,9.946990,9.923880,0.499400,-0.002302,0.496800,0.330300,14.919766,11.759085
std,1.974633,2.012851,0.491128,0.488594,4.030378,4.034053,4.027346,0.500025,1.005845,0.500015,0.470345,4.725965,4.997801
min,-6.601822,-5.702579,0.000000,0.000000,-5.503725,-4.656782,-5.032439,0.000000,-3.678372,0.000000,0.000000,-2.308571,-5.503725
25%,-0.300915,-0.350493,0.000000,0.000000,7.256198,7.225515,7.172954,0.000000,-0.672154,0.000000,0.000000,11.754888,8.306735
50%,1.032543,0.985913,0.000000,0.000000,9.963009,9.995205,9.959684,0.000000,-0.011273,0.000000,0.000000,14.921600,11.428904
75%,2.319681,2.334578,1.000000,1.000000,12.678690,12.709974,12.652646,1.000000,0.674547,1.000000,1.000000,18.095607,14.995862
max,8.355516,8.613754,1.000000,1.000000,24.566237,24.039729,24.633057,1.000000,3.526289,1.000000,1.000000,33.225206,33.225206

In [7]:
df.corr()

,X1,X1_lag,X2,X2_lag,y0,y0_lag_1,y0_lag_2,z,U,D,d,y1,y
X1,1.000000,0.284308,0.007335,0.001230,0.004969,0.020897,0.013754,0.006951,-0.002888,-0.006704,-0.007246,-0.002252,-0.004459
X1_lag,0.284308,1.000000,-0.002579,-0.012452,0.000028,0.008910,0.008340,-0.001747,-0.010746,-0.024415,-0.019153,-0.005966,-0.007068
X2,0.007335,-0.002579,1.000000,0.187625,0.006889,-0.003521,-0.007770,0.000381,-0.013351,-0.017310,-0.013572,-0.002256,-0.001944
X2_lag,0.001230,-0.012452,0.187625,1.000000,0.012096,0.012911,0.012817,-0.000466,0.003258,0.013140,0.001571,0.009878,0.011815
y0,0.004969,0.000028,0.006889,0.012096,1.000000,0.801618,0.643973,0.000976,-0.011477,-0.003107,0.004976,0.848736,0.808160
y0_lag_1,0.020897,0.008910,-0.003521,0.012911,0.801618,1.000000,0.801331,-0.009141,-0.005001,-0.006990,-0.004596,0.686934,0.645514
y0_lag_2,0.013754,0.008340,-0.007770,0.012817,0.643973,0.801331,1.000000,-0.005579,-0.002406,-0.002292,-0.000476,0.554681,0.519708
z,0.006951,-0.001747,0.000381,-0.000466,0.000976,-0.009141,-0.005579,1.000000,-0.016875,0.328799,0.703129,-0.003604,0.367174
U,-0.002888,-0.010746,-0.013351,0.003258,-0.011477,-0.005001,-0.002406,-0.016875,1.000000,0.503446,0.262801,0.306424,0.205024
D,-0.006704,-0.024415,-0.017310,0.013140,-0.003107,-0.006990,-0.002292,0.328799,0.503446,1.000000,0.706795,0.152517,0.365792
d,-0.007246,-0.019153,-0.013572,0.001571,0.004976,-0.004596,-0.000476,0.703129,0.262801,0.706795,1.000000,0.085591,0.525094
y1,-0.002252,-0.005966,-0.002256,0.009878,0.848736,0.686934,0.554681,-0.003604,0.306424,0.152517,0.085591,1.000000,0.808000
y,-0.004459,-0.007068,-0.001944,0.011815,0.808160,0.645514,0.519708,0.367174,0.205024,0.365792,0.525094,0.808000,1.000000

In [8]:
df['X1'].var()

3.899173568893451

In [9]:
df['X1_lag'].var()

4.05156882720308

# используем auto CUPAC

In [11]:
from autocupac import CUPACTransformer

In [12]:
# Инициализация и применение
transformer = CUPACTransformer(target_col='y')
transformer.fit(df)
transformed_data = transformer.transform(df)

# Или одной командой
# transformed_data = transformer.fit_transform(train_data, new_data)

print(transformer.get_report())
print("\nTransformed Data:")
print(transformed_data)

Расширенный CUPAC Report
========================================
Сравнение моделей:
Linear: R²=0.641, Var.Red.=64.2%
Ridge: R²=0.642, Var.Red.=64.2%
Lasso: R²=0.641, Var.Red.=64.2%
CatBoost: R²=0.638, Var.Red.=63.8%

Лучшая модель: Ridge
Снижение дисперсии: 64.2%
Качество предсказания (R²): 0.642

Топ-10 значимых признаков:
- y0_lag_2                    0.803 ▇▇▇▇▇▇▇▇▇▇
- X2_lag                      0.022
- X1_lag                      0.005

Интерпретация:
▇▇▇▇▇▇▇▇▇▇ - максимальное влияние
Коэффициенты > 0: положительная связь с целевой переменной
Коэффициенты < 0: отрицательная связь

Transformed Data:
            X1    X1_lag  X2  X2_lag         y0   y0_lag_1   y0_lag_2  z  \
0     1.407035  2.582219   0       1  10.054458   9.812256   9.592427  1
1     3.850649  2.757775   0       1   5.968851   6.515070   7.316338  0
2     3.287116  3.961634   1       0  11.414347   9.482436   8.523009  1
3     4.293427  0.229035   1       0   6.488326   5.130305  10.111296  1
4    -0.514052  1.328158   1       0  15.660215  13.760201  12.065511  0
...        ...       ...  ..     ...        ...        ...        ... ..
9995  3.520474 -4.682424   0       1  13.058468  12.458144  14.269385  0
9996  0.521618  1.234196   1       1   7.334749   6.297490   9.683512  1
9997  0.147611  0.038316   0       0  17.739514  16.638279  15.206843  0
9998 -1.104853 -1.125026   1       0   5.243255  10.654889   9.740049  1
9999  0.001045  1.717377   0       0   4.462951   6.089241   4.757848  1

             U  D  d         y1          y    y_cupac
0    -1.390216  0  0   8.879218  10.054458  10.169346
1     0.217613  1  0  12.119830   5.968851   8.709457
2     0.636459  1  1  21.528178  21.528178  21.876382
3     0.843316  1  1  14.155339  14.155339  17.979386
4    -1.612887  0  0  17.834407  15.660215  12.604664
...        ... .. ..        ...        ...        ...
9995  0.944870  1  0  18.179192  13.058468  11.047908
9996 -1.656972  0  0   6.711569   7.334749  10.242429
9997 -1.757182  0  0  18.208476  17.739514  12.401337
9998  0.652222  1  1   9.168529   9.168529   8.598954
9999  0.588384  1  1  11.836513  11.836513  14.935031

[10000 rows x 14 columns]

In [13]:
transformed_data.describe()

,X1,X1_lag,X2,X2_lag,y0,y0_lag_1,y0_lag_2,z,U,D,d,y1,y,y_cupac
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1.014193,1.000744,0.406100,0.393700,9.930242,9.946990,9.923880,0.499400,-0.002302,0.496800,0.330300,14.919766,11.759085,11.759085
std,1.974633,2.012851,0.491128,0.488594,4.030378,4.034053,4.027346,0.500025,1.005845,0.500015,0.470345,4.725965,4.997801,3.817295
min,-6.601822,-5.702579,0.000000,0.000000,-5.503725,-4.656782,-5.032439,0.000000,-3.678372,0.000000,0.000000,-2.308571,-5.503725,1.435019
25%,-0.300915,-0.350493,0.000000,0.000000,7.256198,7.225515,7.172954,0.000000,-0.672154,0.000000,0.000000,11.754888,8.306735,9.021053
50%,1.032543,0.985913,0.000000,0.000000,9.963009,9.995205,9.959684,0.000000,-0.011273,0.000000,0.000000,14.921600,11.428904,11.148921
75%,2.319681,2.334578,1.000000,1.000000,12.678690,12.709974,12.652646,1.000000,0.674547,1.000000,1.000000,18.095607,14.995862,14.077516
max,8.355516,8.613754,1.000000,1.000000,24.566237,24.039729,24.633057,1.000000,3.526289,1.000000,1.000000,33.225206,33.225206,28.911660